### ISSUE TITLE
Possible bug in the parallel implementation

### ISSUE THREAD

**Issue by kovla** [simsem/simsem#31]
Hello,

I am using simsem to generate some data for missing data analysis simulations. And first of all I would like to thank you for providing such a flexible and efficient package. 

And now to the problem: 
sim() throws an error when multicore=TRUE. In version 0.5-8 the error is 

```
Error in checkForRemoteErrors(val) : 
1000 nodes produced errors; first error: $ operator not defined for this S4 class
```

and in version 0.5-9 the error is 

```
Error in checkForRemoteErrors(val) : 
1000 nodes produced errors; first error: could not find function "simulateData"
```

In the source code for sim.R I find this line: 

```
 data <- do.call("simulateData", generate) # Change to simulateData when the bug is fixed
```

Since I have to generate data using multiple cores, I am wondering what is the state of affairs in this regard. Is it someting on the short list for being fixed or should one better implement parallelism externally? Also, does this bug influence data generation on a single core? Thank you.

**Comment by psunthud** [comment]
Could you please use the 0.5-13 version and check the problem still exist? I am sorry for taking so long to reply your comment.

https://github.com/simsem/simsem/tree/master/builds
