### ISSUE TITLE
sim(): default value of seed

### ISSUE THREAD

**Issue by kovla** [simsem/simsem#32]
I believe there is a potential source of confusion in sim() version 0.5-9: the default value of seed is set to 123321. I used sim() to run an ML analysis on single dataset, and that operation was then run in parallel. Not the intended use of sim(), perhaps, but it was more convenient in my case than using lavaan directly. 

In either case, I've noticed that, when run in parallel, almost all my results were identical. In the end, it boiled down to specifying seed=NULL as argument. Perhaps the NULL value should be specified by default, as users may be unaware of the current setting.

**Comment by psunthud** [comment]
I am sorry about this delay. Please let me try to understand your issue. You use sim() to run your data set multiple times, don't you? If so, do you have the same data sets and the same script? I just want to make sure that I should expect the same or different results. For the observed data sets, the results should be the same, right?

Regarding to the seed number, we designed the simulation to be replicable. Thus, the seed number is fixed but users can provide different seed numbers.

**Comment by kovla** [comment]
Indeed, with standard use of simsem this is perhaps a more logical behavior. In my case, I used a single sim() run, i.e. generating a single data set, and then ran this operation in parallel. A necessary workaround for me, as I needed to use multiple techniques on each data set (not only ML-based). And given the fixed seed value, these parallel runs gave me same results. It took me some time to realize that there is no error in the code, just a fixed seed argument. Perhaps a small note in the help files about this might avoid confusion for other users in the future. Just a thought. Otherwise, a very flexible and useful package, thank you!

**Comment by mronkko** [comment]
I am running same kind of setup as kovla (use the same sample with different estimator), and I have found the current design really good for this purpose. So I can do

sim(... model = myEstimatorFunction1())
sim(... model = myEstimatorFunction2())
sim(... model = myEstimatorFunction3())
 
and be sure that each estimator is evaluated with the exact same samples. Another design that I have used is to simply generate the samples as list, and then apply the estimators to the list of data outside simsem.

**Comment by kovla** [comment]
@mronkko Actually, my setup is more like this (code a bit pseudo-ish): 

```r
runSimulation <- function(n,dataModel, analysisModel, missingModel, methods=c("ml","lm")) {
library(simsem)
library(mice)

    runOnce <- function(n,dataModel, analysisModel, missingModel, methods=c("ml","lm")) {
    data <- generate(model=dataModel, n = sampleSize)
    data <- imposeMissing(data, logit=missingModel)

    ...
    ml.result <- sim(model = sem.model, rawData = list(data), lavaanfun = 'sem',
                                 silent = TRUE, missing = "fiml", information="observed",
                                 estimator="ML", seed=NULL) # seed must be NULL, otherwise identical
                                                            # results as the value is set by default
                                                            # in sim()
    # other methods, e.g. lm()
    ...
    return(list(ml.result,lm.result))
    }

# parallel execution
library(parallel)
...
unsorted.result <- parLapply(cl, seq_len(nSamples), runOnce, sampleSize = sampleSize, 
                                 dataModel=dataModel, missModel = missingModel, 
                                 analysisModel = analysisModel, trueValues = trueValues,
                                 method=method)
return(unsorted.result)
}
```

The issue was that the elements of unsorted.result were mostly identical, since the seed in the runOnce() function was fixed. Once I specified seed = NULL, the code ran as it should. @psunthud  is correct in that such situation would not appear with normal sim() use.

**Comment by mronkko** [comment]
Why not just do something like this:

´´´´
dataList <- generate(model=dataModel, n = sampleSize, reps = 1000)

dataList <- lapply(dataList, imposeMissing, logit=missingModel)

    ...
ml.results <- sim(model = sem.model, rawData = dataList, lavaanfun = 'sem',
                                 silent = TRUE, missing = "fiml", information="observed",
                                 estimator="ML", seed=NULL) # seed must be NULL, otherwise identical
                                                            # results as the value is set by default
                                                            # in sim()
    # other methods, e.g. lm()
    ...
´´´´

This is what I do.

**Comment by kovla** [comment]
I can't remember exactly, as some time has passed now since I wrote that. I believe that sim() threw an error when I tried to use its internal parallel implementation, so I worked around that. Also, there is no `reps=` argument in generate. So it seemed easier to aggregate all the statistical processing in one step and parallelize in another.

**Comment by mronkko** [comment]
Yes, my code was a bit pseudo code. Here is a proper call for generating a list of data sets in parallel.

```r
dataList  <- sim(nRep = 1000, model = dataModel, n = sampleSize, multicore = TRUE, dataOnly=TRUE) 
```

The internal multicore works well for me.

**Comment by kovla** [comment]
```r
dataList  <- sim(nRep = 1000, model = dataModel, n = 300, multicore = TRUE, dataOnly=TRUE) 

# Error in sim(nRep = 1000, model = dataModel, n = 300, multicore = TRUE,  : 
# could not find function "is.partable"
```
This is simsem v. 0.5-9 on Windows 7 64-bit. The previous version also gave an error, albeit a different one. Anyway, I've got a working code now, it's just that if the seed being fixed was explicitly mentioned in the help file text, I'd figured my issue sooner. Thanks for your input!

**Comment by psunthud** [comment]
I have added more description in the seed argument as follows:

  \item{seed}{ 
	Random number seed. Note that the seed number is always fixed in the \code{simsem} so that users can always replicate the same simulatin or can be confidence that the same data set are generated. Reproducibility across multiple cores or clusters is ensured using R'Lecuyer package.
}

If you have any recommendation, please let me know.
