### ISSUE TITLE
User constrained parameters are not stored

### ISSUE THREAD

**Issue by mronkko** [simsem/simsem#33]
The current github version of simsem does not store user constrained parameter values. For example, if I identify a three indicator factor model by fixing the first indicator, only two factor loadings are reported in the results. With raw estimates this is obviously not need because the mean will be the value that I fixed and sd will be zero. However, sometimes a researcher is interested in standardized estimates and in this scenario the mean and sd of the fixed parameters are informative.

This can be implemented by changing the line 1033 in sim.R to
```
index <- ((outpt$free != 0) & !(duplicated(outpt$free))) | extraParamIndex | (outpt$user == 1 & outpt$start !=0) 
```
Also, line 1043
```
lab <- lavaan::lav_partable_labels(lapply(changept, "[", changept$free > 0 | (outpt$user == 1 & outpt$start !=0))
```

**Comment by psunthud** [comment]
Thank you! I have changed it in the latest version.
