### ISSUE TITLE
Bug: generating data with a single factor in SimSem style

### ISSUE THREAD

**Issue by patr1ckm** [simsem/simsem#35]
An email from Dexin Shi:

 When trying to generate data from a single factor measurement model below:

    library(simsem)
    loading <- matrix(c(0.7,0.6,0.7,0.6,0.7,0.8), 6, 1)
    LY <- bind(loading)
    TE <- binds(diag(6)*0.3)
    TY <- bind(matrix(c(0,0,0,0,0,0), 6, 1))
    VE<-bind(matrix (1))
    ME<-bind(matrix (0))
    RPS <- binds(as.matrix(1))
    CFA.Model <- model(LY = LY, TE = TE,TY=TY,VE=VE,ME=ME,RPS=RPS, modelType = "CFA")
    dat <- generate(CFA.Model,n=300)

Produces the error message 

     "Error in max.path[var.dv == 0, ] <- abs.path[var.dv == 0, ] : 
    incorrect number of subscripts on matrix". 

It looks like the model is specified correctly. Looks like a we may need [,drop=FALSE] somewhere?

**Comment by t129j179** [comment]
Yes, it occurs on line 52 of validate.R, in the validatePath() function.  I will submit a change for Sunthud to approve.

**Comment by patr1ckm** [comment]
with simsem 0.5-12, it now produces

`Error in round(abs.path, 6) > round(max.path, 6) : non-conformable arrays`

**Comment by t129j179** [comment]
I added another "drop = FALSE" on the same line for max.path like I did for abs.path.  Don't know why I didn't to begin with, and I hope that does the trick.

**Comment by psunthud** [comment]
The problem fixed in the latest version.
