### ISSUE TITLE
Bug: setPopulation with lavaan model

### ISSUE THREAD

**Issue by patr1ckm** [simsem/simsem#36]
popModel <- "
    f1 =~ 0.7*y1 + 0.7*y2 + 0.7*y3
    f2 =~ 0.7*y4 + 0.7*y5 + 0.7*y6
    f1 ~~ 1*f1
    f2 ~~ 1*f2
    f1 ~~ 0.5*f2
    y1 ~~ 0.51*y1
    y2 ~~ 0.51*y2
    y3 ~~ 0.51*y3
    y4 ~~ 0.51*y4
    y5 ~~ 0.51*y5
    y6 ~~ 0.51*y6
    y7 ~~ 1*y7
    y1 ~~ 0.40*y7
    y2 ~~ 0.40*y7
    y3 ~~ 0.40*y7
    y4 ~~ 0.40*y7
    y5 ~~ 0.40*y7
    y6 ~~ 0.40*y7
    "

    analyzeModel <- "
    f1 =~ y1 + y2 + y3
    f2 =~ y4 + y5 + y6
    "

    missmodel <- miss(pmMAR=0.5, cov="y7", threshold = 0.5)

    Output <- sim(10, analyzeModel, n=200, generate=popModel, std.lv=TRUE, lavaanfun = "cfa", miss =   missmodel)
    Output <- setPopulation(Output,popModel)

Produces the error:

    Error in setPopulation(Output, popModel) : 
       trying to get slot "dgen" from an object of a basic class ("character") with no slots

Shouldn't be too bad of a fix. Just need to extract population parameters from the lavaan model in 'generate', returning the population parameters as a list item $psl.

**Comment by psunthud** [comment]
The problem fixed in the latest version.
