### ISSUE TITLE
Bug: Example 10 SimSem style

### ISSUE THREAD

**Issue by patr1ckm** [simsem/simsem#37]
Running [ex10](https://github.com/simsem/simsem/blob/master/SupportingDocs/Examples/Version03/ex10/ex10.R) in SimSem style produces the following error:

    Error in attachPT(model, indName, "~~", aux, ngroups) : 
      negative length vectors are not allowed
    In addition: Warning messages:
    1: In max(pt$unco) : no non-missing arguments to max; returning -Inf
    2: In max(pt$unco) : no non-missing arguments to max; returning -Inf

**Comment by t129j179** [comment]
The error occurs on line 544 of model.R, in the hidden parseFree function.  There is no longer an "unco" column in the lavaan parameter table, but a "plabel" column might need to be added.

**Comment by t129j179** [comment]
It looks like this was resolved, no more error for this example.
