### ISSUE TITLE
Multiple imputation is not applied to function analysis

### ISSUE THREAD

**Issue by mronkko** [simsem/simsem#38]
In the current implementation, multiple imputation is applied in the analyzeLavaan function. It would be useful if MI was applied in the sim function instead before calling any of the estimation functions. Most importantly, I would prefer to apply MI to function analysis without having to implement it inside the function.

**Comment by t129j179** [comment]
Looking at the implementation, I would recommend implementing MI in the a separate function, which can be passed to `sim()` via the `datafun` argument. Currently, missing data are imposed before the `datafun` argument is applied to the (generated) data.  So if your `datafun` returns a list of imputed data sets, that just needs to be the first argument of your `model` function (which can now accept other arguments via `...`).
