### ISSUE TITLE
Bug: lavaan syntax for sim(..., generate = ) argument

### ISSUE THREAD

**Issue by t129j179** [simsem/simsem#39]
Check out the problem reported here:

https://groups.google.com/d/msg/lavaan/x8XaBo7E0CQ/bJDxaWJABgAJ

An error is returned when using lavaan syntax for the population (and analysis) models.  I tracked down the error to line 753 in sim.R, when the runRep() function tries to extract the model-implied moments using the fitted() method.  lavInspect() could be used instead, but might require formatting the list in a way expected later in the function.

The problem does not occur when using the LISREL matrices instead of lavaan syntax (see example in my reply at the above link).

**Comment by patr1ckm** [comment]
+1 on this, got another email.

**Comment by patr1ckm** [comment]
Here's the example in full as well

    library(simsem)

    popModel <- "
    f1 =~ 0.7*y1 + 0.7*y2 + 0.7*y3
    f2 =~ 0.7*y4 + 0.7*y5 + 0.7*y6
    f1 ~~ 1*f1
    f2 ~~ 1*f2
    f1 ~~ 0.5*f2
    y1 ~~ 0.49*y1
    y2 ~~ 0.49*y2
    y3 ~~ 0.49*y3
    y4 ~~ 0.49*y4
    y5 ~~ 0.49*y5
    y6 ~~ 0.49*y6
    "

    analysisModel <- "
    f1 =~ y1 + y2 + y3
    f2 =~ y4 + y5 + y6
    f1 ~~ 1*f1
    f2 ~~ 1*f2
    f1 ~~ f2
    y1 ~~ y1
    y2 ~~ y2
    y3 ~~ y3
    y4 ~~ y4
    y5 ~~ y5
    y6 ~~ y6
    "

    dist2 <- bindDist(skewness = seq(-3, 3, length.out=6), kurtosis = seq(2, 5, length.out=6))
    summary(dist2)

    Output <- sim(5, model=analysisModel, n=150, generate=popModel, std.lv=TRUE, lavaanfun = "cfa",      indDist = dist2)

Produces

      Error: $ operator not defined for this S4 class

The error does not occur when "inDist" is dropped.

Like you say Terry, I'm sure it's here in runRep

	if(!is.null(indDist)) {
			generate$return.fit <- TRUE
			data <- do.call("simulateData", generate) # Change to simulateData when the bug is fixed
			implied <- fitted(attr(data, "fit"))
			if(length(n) == 1) implied <- list(implied)
			datinddist <- NULL
			for(i in seq_along(n)) datinddist <- rbind(datinddist, dataGen(indDist, n[i], implied[[i]]$mean, implied[[i]]$cov))
			datinddist <- as.data.frame(datinddist)
			datinddist$group <- rep(1:length(n), times=n)
		} else {
			data <- do.call("simulateData", generate) # Change to simulateData when the bug is fixed
		}
	}

**Comment by psunthud** [comment]
Problem fixed. I put the wrong argument name in the simulateData function.
