### ISSUE TITLE
Example 25; simsem matrix specification 

### ISSUE THREAD

**Issue by ayo** [simsem/simsem#42]
Hi,
These are lines 55 and 56 in the code for example 25 

55.  outDatNestedModNested <- sim(NULL, n=50:500, longNested, generate = longNested) 
56. outDatNestedModParent <- sim(NULL, n=50:500, longParent, generate = longNested)

what does the NULL argument do on lines 55 and 56? when I run that line I get some weird results. NReps becomes 451 when it should be 500. .

Are these errors in the code, or am I  missing something?  

Thanks for making Simsem available.

**Comment by t129j179** [comment]
Hi ayo,

The descriptions of the nRep and n arguments on the ?sim help page explain this.  When you specify a vector of sample sizes for "n", then one replication will be simulated at each level.  There are 451 elements in the vector 50:500.
