### ISSUE TITLE
Use explicit namespace in do.call function calls

### ISSUE THREAD

**Issue by mronkko** [simsem/simsem#43]
All do.call function calls should have explicit namespaces. For example

`do.call("simulateData", generate)`

Should be

`do.call("simsem::simulateData", generate)`

There are two reasons for this:

1. A user may call simsem functions directly without loading the library (e.g. simsem::sim)
2. A user could have loaded a package that provides a "simulateData" function

**Comment by psunthud** [comment]
Thank you! I have fixed it.
