### ISSUE TITLE
summaryParam does not work when SEs are not available

### ISSUE THREAD

**Issue by mronkko** [simsem/simsem#44]
Here is a testcase for you

```
pop <- data.frame(y1 = rnorm(100000, 0, 1), y2 = rnorm(100000, 0, 1))

analyzeFUN <- function(data) {
  out <- lm(y2 ~ y1, data=data)
  coef <- coef(out)
  se <- sqrt(diag(vcov(out)))
  se[1:2] <- NA
  fit <- c(loglik = as.numeric(logLik(out)))
  converged <- TRUE # Assume to be convergent all the time
  return(list(coef = coef, se = se, fit = fit, converged = converged))
}

Output <- sim(5, model=analyzeFUN, n=200, rawData=pop, lavaanfun = "cfa")
summary(Output)
```

The problem is caused by the crit scalar being defined inside a block that is executed only if SEs are available. However, the crit scalar is later used without checking the SEs when calculating CIs

https://github.com/simsem/simsem/blob/master/simsem/R/summarySimResult.R

A one line fix would be to move line 25 outside the if block

`crit <- qnorm(1 - alpha/2)`

A better way would be to not try to calculate CIs at all when SEs are not available, but this would require more changes.

Mikko

**Comment by t129j179** [comment]
Thanks for the suggestion.  Both `crit` and `estimated.se` are now defined above that if-block, and your example works now.  The development version can be installed with `devtools::install_github("simsem/simsem/simsem")`, but it should not be long until we submit a new version to CRAN.
