### ISSUE TITLE
Pass additional parameter to function analysis

### ISSUE THREAD

**Issue by mronkko** [simsem/simsem#46]
Function analysis is currently implemented in runRep as follows:

```
        if(is(model, "function")) {
            if(stopOnError){
            out <- model(data)
            } else if (silent) {
                invisible(capture.output(suppressMessages(try(out <- model(data), silent = TRUE))))
            } else {
                try(out <- model(data))
            }
        }
```

This could be enhanced by adding ellipsis in the function calls to pass additional parameters

```
        if(is(model, "function")) {
            if(stopOnError){
            out <- model(data, ...)
            } else if (silent) {
                invisible(capture.output(suppressMessages(try(out <- model(data, ...), silent = TRUE))))
            } else {
                try(out <- model(data, ...))
            }
        }
```

This would be very useful because it would allow specifying generic estimation functions. For example, suppose that I want to assess the performance of MIIVsem package using simsem. I can do this by using function analysis, but would need to hard code my model into the estimation function. It would be convenient if I could just write one estimation function, to which I can pass the estimated model as a parameter.

For example, I could run

```
sim(5, model =myGenericMIIVsemFunction, generate = CFA.Model, n=200,  miiv.model=mySpecificMIIVsemModel)
```

where `myGenericMIIVsemFunction` is a function that would estimate `mySpecificMIIVsemModel` using the data generated by simsem

**Comment by t129j179** [comment]
This is a great idea -- now available in the development version via github.
