### ISSUE TITLE
Problem using the rawData argument

### ISSUE THREAD

**Issue by FloSchuberth** [simsem/simsem#47]
Hey, 
I try to replicate your example from the Wiki:
https://github.com/simsem/simsem/wiki/Example-2:-Getting-Started-(lavaan-input)

    library(simsem)

    varnames <- c("x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9")
    cm <- cov(HolzingerSwineford1939[,varnames])
    library(MASS)
    dataList <- list()
    for(i in 1:1000) {
     dataList[[i]] <- mvrnorm(200, rep(0, 9), cm) 
    }

    analyzeModel <- "
    f1 =~ x1 + x2 + x3
    f2 =~ x4 + x5 + x6
    f3 =~ x7 + x8 + x9
    "

    Output <- sim(NULL, model = analyzeModel, rawData = dataList, lavaanfun = "cfa")

But I get the following error message:

     Error in names(coef) <- lab : 
      'names' attribute [24] must be the same length as the vector [21]

I use the latest version of simsem: 

     citation('simsem')
    @Manual{,
      title = {simsem: SIMulated Structural Equation Modeling},
      author = {Sunthud Pornprasertmanit and Patrick Miller and Alexander Schoemann},
      year = {2016},
      note = {R package version 0.5-14},
      url = {http://www.simsem.org},
     }

Can you please give me any advice?
Best regards, 
Florian Schuberth

**Comment by M-E-Steiner** [comment]
I have the same issue.

I could at least pinpoint the line of code where the error occures but I dont see a quick fix: the error happens
within the `runRep()` function in line `464: names(coef) <- lab`. Obviously `lab` doesnt have the same lenght as `names(coef)`. Could one of the maintainers please check that?

**Comment by t129j179** [comment]
I think this error was already fixed, but a later development version of simsem has been built.  Could you install 0.5-14 in the Builds folder and try again?  I can run this example without error, using R 3.3.2, lavaan 0.5-23.1044 (also development version), and simsem 0.5-14, and the only warning is about the occasional negative residual variance.

**Comment by M-E-Steiner** [comment]
I installed the newest version from github using `devtools`

    require(devtools)
    install_github("simsem/simsem/simsem")

Now it works. Thanks for your help.

**Comment by FloSchuberth** [comment]
Thank you!
