### ISSUE TITLE
Simsem : CFA syntax issue

### ISSUE THREAD

**Issue by dgroy81** [simsem/simsem#49]
I am PhD scholar who is using R simsem package for Data generation. I am using the simsem::model function and created the matrix using the help document. However I am getting this error message  at the end.

 CFA.Model <- simsem::model(LY = LY, RPS = RPS, RTE = RTE, modelType = "CFA")
Error in buildModel(paramSet, modelType) :
  The error correlation (RTE) matrix must be symmetric.

I used the same script on the document page and it threw the same error. Seems the error is with R engine. can you kindly help me out?

=====================================
My Code
-========================================
******Matrix**************
loading <- matrix(0,36, 6)
loading[1:6, 1] <-  c(1, 0.7, 0.7, 0.8, 0.8, 0.8)
loading[7:12, 2] <- c(1, 0.9, 0.7, 0.7, 0.8, 0.8)
loading[13:18, 3] <-  c(1,0.9, 0.7, 0.9, 0.6, 0.9)
loading[19:24, 4] <-  c(1, 0.9,0.9, 0.9, 0.9, 0.9)
loading[25:30, 5] <-  c(1, 0.9, 0.9, 0.9, 0.5, 0.5)
loading[31:36, 6] <-  c(1, 0.9, 0.9, 0.9, 0.9, 0.9)

LY <- simsem::bind(loading)

************covariance matrix************

facCov <- matrix(NA, 6, 6)
facCovVal <- diag(c(0.8, 0.9, 0.7,0.8,0.6,0.7))
facCovVal[lower.tri(facCovVal)] <- c(0.5, 0.4, 0.5)
facCovVal[upper.tri(facCovVal)] <-  c(0.5, 0.4, 0.5)
PS <- simsem::bind(facCov, facCovVal)

errorCov <-matrix(NA, 36,36)
errorCovVal <- diag(c(0.5, 0.3, 0.8, 0.4, 0.4, 0.7, 0.6, 0.5, 0.6,0.7,0.8,0.3,0.2,0.1,0.5,0.6,0.7,0.8,0.5, 0.3, 0.8, 0.4, 0.4, 0.7, 0.6, 0.5, 0.6,0.5, 0.3, 0.8, 0.4, 0.4, 0.7, 0.6, 0.5, 0.6))
TE <- simsem::bind(errorCov, errorCovVal)

************Model building**************
CFA.Model <- simsem::model(LY=LY, PS=PS, TE=TE, modelType="CFA")

The examples in https://github.com/simsem/simsem/wiki/Example-1:-Getting-Started and 

https://github.com/simsem/simsem/wiki/Example-2:-Covariance-Matrix-Specification

do not work as well.

**Comment by dgroy81** [comment]
I tried to debug and did not find adequate number of documents. It is my first time and the direct answer to this problem is always to check the matrix symmetry and I am already sure about the correctness of my matrix frame.

errorCov <-matrix(NA, 36,36)
errorCovVal <- diag(c(0.5, 0.3, 0.8, 0.4, 0.4, 0.7, 0.6, 0.5, 0.6,0.7,0.8,0.3,0.2,0.1,0.5,0.6,0.7,0.8,0.5, 0.3, 0.8, 0.4, 0.4, 0.7, 0.6, 0.5, 0.6,0.5, 0.3, 0.8, 0.4, 0.4, 0.7, 0.6, 0.5, 0.6))
TE <- simsem::bind(errorCov, errorCovVal)

I tried this code https://rdrr.io/cran/simsem/src/R/model.R...and saw nothing important here.

**Comment by TDJorgensen** [comment]
You are not using the `symmetric = TRUE` argument to the `bind()` function.  Equivalently, you could just use the `binds()` function for symmetric matrices.  In your example above
```
TE <- bind(errorCov, errorCovVal, symmetric = TRUE) # or binds(errorCov, errorCovVal)
PS <- bind(facCov, facCovVal, symmetric = TRUE) # or binds(facCov, facCovVal)
```
I still get an error with your definition of `PS`, but that is because you are not supplying a symmetric matrix.  You can see which entries are not symmetric by checking whether it is equal to its transpose:
```
facCovVal == t(facCovVal)
```
Notice that [2, 4] is 0.4, which is not equal to [4, 2] (0.5).

Also, your model will not be identified (so you will run into more problems later) because you are trying to estimate every element in TE and PS.  And you are not supplying a matrix of population values to LY, just fixing every value.

**Comment by dgroy81** [comment]
Thanks for your insight. I guess I know the problem now. 
But what if I use the following definition? Why it is giving an error in this case.

latent.cor <- matrix(NA, 6, 6)
diag(latent.cor) <- 1
RPS <- simsem::bind(latent.cor, 0.5)

RTE <- simsem::bind(diag(36))
Can you kindly point me to a documentation for larger matrix? 
Thanks in advance for clearing my doubt.

**Comment by dgroy81** [comment]
Note:: bind is not working in R 3.2.5

**Comment by seonghobae** [comment]
Do update the R if you do not have any particular reasons.

**Comment by dgroy81** [comment]
Thank you all for your helps. I am too surprised that a quick fixes in the numbers and the new R version worked smoothly for me. Utterly grateful.

**Comment by dgroy81** [comment]
Hello,

How to fix a constraint so that the data generated are all positive. I am getting a mixed values of positive and negatives.

**Comment by TDJorgensen** [comment]
A little context would help.  What is wrong with negative data values?  If you are specifying population means of zero (or implicitly letting them be zero by not specifying any mean structure), then of course you must expect half of the data to be below zero and half to be above zero.

**Comment by dgroy81** [comment]
I understand that, the dispersion is the reason behind the  combination , for achieving a mean. But I need a positive value set for my purpose. And i did not specify population mean. Is there anyway to keep a population mean ==3 or 4?

**Comment by TDJorgensen** [comment]
You can set the item intercepts (TY vector) to whatever you want the means to be (e.g., 10, to make sure a negative observation is sufficiently improbably).

https://github.com/simsem/simsem/wiki/Example-3:-Model-Misspecification
