### ISSUE TITLE
Error in drawParam :Cannot obtain valid parameter set within maximum number of draw

### ISSUE THREAD

**Issue by dgroy81** [simsem/simsem#50]
Hi ,
For a specific sample I need to generate a distribution of positive data in 6 X 6 matrix.

When I add these lines to specify the intercept ,the snippet is working fine

factor.mean <- rep(NA, 6)
factor.mean.starting <- c(2,3,3,3,3,2)
AL <- simsem::bind(factor.mean, factor.mean.starting)

However while generating data I am getting this error message:

> dat <- simsem::generate(CFA.Model, 500)
******Error in drawParam(model@dgen, maxDraw = maxDraw, numFree = max(model@pt$free),  : 
  Cannot obtain valid parameter set within maximum number of draws.***********

I checked out the code in https://github.com/simsem/simsem/blob/master/simsem/man/draw.Rd  and found a similar kind of message       "	Integer specifying the maximum number of attempts to draw a valid set of parameters (no negative error variance, standardized coefficients over 1). 

Can anybody kindly give me a pointer? Is it because it cannot generate ample number of samples
? Or do I need to fix factorCov and ErrorCov in certain ways?

Thanks in advance!

**Comment by TDJorgensen** [comment]
Need more context

**Comment by dgroy81** [comment]
I am trying to generate a model with 6 nodes , which in turn has 6 sub-nodes each. the 6 sub-nodes will have data from 1 to 5 scale. So the values can be 1 to 5 . Is it possible to generate this kind of data using simsem. the factor wight of each node should be more than 0.5.

This is my over all criteria.

**Comment by TDJorgensen** [comment]
Could you please post a syntax example that reproduces your problem?

**Comment by dgroy81** [comment]
==================================================
Matrix 6*6
================================================
loading <- matrix(0,36, 6)
loading[1:6, 1] <-  c(1, 0.9, 0.9, 0.9, 1.0, 0.9)
loading[7:12, 2] <- c(1, 0.9, 0.8, 0.8, 0.8, 0.9)
loading[13:18, 3] <-  c(1,0.9, 0.8, 0.9, 0.8, 0.9)
loading[19:24, 4] <-  c(1, 0.9,0.9, 0.9, 0.9, 0.9)
loading[25:30, 5] <-  c(1, 0.9, 0.9, 0.9, 0.8, 0.8)
loading[31:36, 6] <-  c(1, 0.9, 0.9, 0.9, 0.9, 0.9)


LY <- simsem::bind(loading)

#################################
Mean value to retrict values from 1 to 5
##################################

factor.mean <- rep(NA, 6)
factor.mean.starting <- c(2,3,3,3,3,2)
AL <- simsem::bind(factor.mean, factor.mean.starting)

##################################
Factor cov and error cov 
#################################

facCov <- matrix(NA, 6, 6)
facCovVal <- diag(c(0.8, 0.9, 0.7,0.8,0.6,0.7))
facCovVal[lower.tri(facCovVal)] <- c(0.9, 0.9, 0.9)
facCovVal[upper.tri(facCovVal)] <-  c(0.9, 0.9, 0.9)
facCovVal == t(facCovVal)
PS <- simsem::bind(facCov, facCovVal,symmetric = TRUE)

errorCov <-matrix(NA, 36,36)
errorCovVal <- diag(c(1.2, 1.1, 1.2, 1.3, 1.2, 1.3, 1.2, 1.1, 1.2,1.3,1.2,1.4,1.2,1.1,1.2,1.5,1.2,1.2,1.2, 1.2, 1.5, 1.2, 1.1, 1.2,1.4, 1.2, 1.3,1.2, 1.1, 1.2, 1.3, 1.2, 1.3,1.2, 1.1, 1.2))
errorCovVal == t(errorCovVal)
TE <- simsem::bind(errorCov, errorCovVal,symmetric = TRUE)


#################################
Model generation
##################################

CFA.Model <- simsem::model(LY=LY, PS=PS, TE=TE, AL=AL, modelType="CFA")
dat <- simsem::generate(CFA.Model, 500)



I am deeply touched for your repeated helps

facCov <- matrix(NA, 6, 6)
facCovVal <- diag(c(0.8, 0.9, 0.7,0.8,0.6,0.7))
facCovVal[lower.tri(facCovVal)] <- c(0.9, 0.9, 0.9)
facCovVal[upper.tri(facCovVal)] <-  c(0.9, 0.9, 0.9)
facCovVal == t(facCovVal)
PS <- simsem::bind(facCov, facCovVal,symmetric = TRUE)

errorCov <-matrix(NA, 36,36)
errorCovVal <- diag(c(1.2, 1.1, 1.2, 1.3, 1.2, 1.3, 1.2, 1.1, 1.2,1.3,1.2,1.4,1.2,1.1,1.2,1.5,1.2,1.2,1.2, 1.2, 1.5, 1.2, 1.1, 1.2,1.4, 1.2, 1.3,1.2, 1.1, 1.2, 1.3, 1.2, 1.3,1.2, 1.1, 1.2))
errorCovVal == t(errorCovVal)
TE <- simsem::bind(errorCov, errorCovVal,symmetric = TRUE)

CFA.Model <- simsem::model(LY=LY, PS=PS, TE=TE, AL=AL, modelType="CFA")
dat <- simsem::generate(CFA.Model, 500)

**Comment by TDJorgensen** [comment]
Try providing a `PS` matrix that is actually possible.  The one you specified is nonpositive definite, which is why data cannot possibly be generated from it.
```
det(facCovVal)
```

**Comment by dgroy81** [comment]
I am extremely grateful. Worked after few manipulations. Thanks a ton
