### ISSUE TITLE
Asymmetrical Matyrix data generation

### ISSUE THREAD

**Issue by dgroy81** [simsem/simsem#51]
Hi,

How to generate the factor variance and error covariance and factor mean data for asymmetrical matrix?

I have a matrix structure like this 
Construct 1: 6 items
Construct 2: 9 items
Construct 3: 10 items
Construct 4; 7 items
Construct 5; 4 items 
Construct 6: 10 items

Is there any general syntax for factor variance and error covariance and factor mean data  in simsem? The documentation on simsem.org is bit rigid in terms of varieties of example in context of asymmetrical matrices.

**Comment by dgroy81** [comment]
Is it possible to construct such a data-matrix? A confirmation will be helpful.

**Comment by mronkko** [comment]
A covariance matrix that is not symmetric cannot be a valid covariance matrix, so the answer to the question as presented is "no". If you mean whether it is possible to have a different number of items for each factor, then the answer is yes

**Comment by dgroy81** [comment]
How to achieve it? I need to have a asymmetric matrix. What should I do?

**Comment by dgroy81** [comment]
I have this requirement:

Construct 1: 6 items
Construct 2: 9 items
Construct 3: 10 items
Construct 4; 7 items
Construct 5; 4 items
Construct 6: 10 items

**Comment by mronkko** [comment]
You do not have an asymmetric matrix. If you want have different numbers of indicators for each factor, just change the number of indicators. 

For example here: 

https://github.com/simsem/simsem/wiki/Example-17:-Select-a-set-of-variables-for-analysis

You can just delete indicators for some of the factors and add more to others. Just be sure that the dimensions of the matrices that you specify match the total number of factors and indicators.

**Comment by dgroy81** [comment]
Thanks a ton. I was not sure of it. Thanks a bunch, really grateful.

**Comment by dgroy81** [comment]
Hi ,

A little help required to debug. I am posting a code snippet here

loadingVal <- matrix(0, 34, 6)
loadingVal[1:5, 1] <- c(1,0.6, 0.7,0.6,0.7)
loadingVal[6:11, 2] <- c(1,1.1, 0.9,0.9,0.7,0.8)
loadingVal[12:17, 3] <- c(1,1.2, 1.1,0.8,0.3,0.5)
loadingVal[18:22, 4] <- c(1,1.1, 0.4, 0.3,0.9)
loadingVal[23:25, 5] <- c(1,1.1, 1.2)
loadingVal[26:34, 6] <- c(1,0.5, 1.0,0.5,0.5,0.9,07,0.7,0.7)

LY <- simsem::bind(loading, "runif(1, 0.4, 0.9)")

factor.mean <- rep(NA, 6)
factor.mean.starting <- c(2,3,3,3,3,2)
AL <- simsem::bind(factor.mean, factor.mean.starting)

W <- matrix(NA, 6, 6)
W <- diag(c(1,1,1,1,1,1))
W[lower.tri(facCovVal)] <- c(0.4, 0.3, 0.3, 0.2, 0.3, 0.2,0.4, 0.3, 0.3, 0.2, 0.3, 0.2,0.3, 0.3, 0.2)
BE <- simsem::bind(W )

RPS <-simsem::bind(diag(6),symmetric = TRUE)

RTE <-simsem::bind(diag(34),symmetric = TRUE)

CFA.Model <- simsem::model(LY=LY, BE=BE, RPS=RPS, RTE=RTE, AL= AL ,modelType="SEM")
data <- simsem::generate(CFA.Model, 410)
write.table(data, file="data.csv", quote=F)


Out put is throwing the following errors 

del(LY=LY, BE=BE, RPS=RPS, RTE=RTE, AL= AL ,modelType="CFA")
Error in `diag<-`(`*tmp*`, value = paramSet$VY@free) : 
  replacement diagonal has wrong length
> CFA.Model <- simsem::model(LY=LY, BE=BE, RPS=RPS, RTE=RTE, AL= AL ,modelType="SEM")
Error in `diag<-`(`*tmp*`, value = paramSet$VY@free) : 
  replacement diagonal has wrong length
> 


Why it is showing this?

**Comment by dgroy81** [comment]
> PS
     [,1]     [,2]     [,3]     [,4]     [,5]     [,6]    
[1,] "NA:0.4" "NA:0.1" "NA:0.1" "NA:0.1" "NA:0.1" "NA:0.1"
[2,] "NA:0.1" "NA:0.3" "NA:0.1" "NA:0.1" "NA:0.1" "NA:0.1"
[3,] "NA:0.1" "NA:0.1" "NA:0.3" "NA:0.1" "NA:0.1" "NA:0.1"
[4,] "NA:0.1" "NA:0.1" "NA:0.1" "NA:0.3" "NA:0.1" "NA:0.1"
[5,] "NA:0.1" "NA:0.1" "NA:0.1" "NA:0.1" "NA:0.3" "NA:0.1"
[6,] "NA:0.1" "NA:0.1" "NA:0.1" "NA:0.1" "NA:0.1" "NA:0.2"
> 


> BE
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]  1.0  0.0  0.0  0.0  0.0    0
[2,]  0.4  1.0  0.0  0.0  0.0    0
[3,]  0.3  0.2  1.0  0.0  0.0    0
[4,]  0.3  0.4  0.2  1.0  0.0    0
[5,]  0.2  0.3  0.3  0.3  1.0    0
[6,]  0.3  0.3  0.2  0.3  0.2    1
> AL
[1] "NA:2" "NA:3" "NA:3" "NA:3" "NA:3" "NA:2"
> RPS
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    0    0    0    0    0
[2,]    0    1    0    0    0    0
[3,]    0    0    1    0    0    0
[4,]    0    0    0    1    0    0
[5,]    0    0    0    0    1    0
[6,]    0    0    0    0    0    1


These are the input matrices.

**Comment by TDJorgensen** [comment]
Your syntax example is incomplete.  When I try to run it, R cannot find objects called `loading` or `facCovVal`. I am glad you are learning to post examples to make yourself understood, but you need to make sure they are reproducible in a fresh R session. A good way to do this is to run 
```
rm(list = ls())
```
and then run your example syntax.  It looks like you need to update 2 lines of syntax:
```
## 'loadingVal' instead of 'loading'
LY <- simsem::bind(loadingVal, "runif(1, 0.4, 0.9)")
```
and 
```
## 'W' instead of 'facCovVal'
W[lower.tri(W)] <- c(0.4, 0.3, 0.3, 0.2, 0.3, 0.2,0.4, 0.3, 0.3, 0.2, 0.3, 0.2,0.3, 0.3, 0.2)
```

That being said, I think your problem is that you are setting the diagonal of the Beta matrix to 1 instead of zero.   If you don't understand why that is a problem, you should invest some time into reading a good book about SEM (e.g., Ken Bollen's (1989) *Structural Equations with Latent Variables*) before trying to simulate data from LISREL models.

**Comment by mronkko** [comment]
More generally, the Lavaan email list may be a better place to ask this kind of question than the GitHub issue tracker.

https://groups.google.com/forum/#!forum/lavaan

**Comment by dgroy81** [comment]
Thank you all for the insights. I am learning and it is a great help to give a guidance about the discussion forum and the book.
