### ISSUE TITLE
Data simulation with moderating moderation and categorical variables.

### ISSUE THREAD

**Issue by dgroy81** [simsem/simsem#53]
![simsem_model](https://user-images.githubusercontent.com/32986977/37518336-bac11698-293a-11e8-9a0f-e466e790a206.png)

Hi all,

Can anybody kindly point out how to simulate the data for the attached model . I want to provide given factor loadings and covariance matrix for each of  the factors.

Previously I created a simulation of this sort with the following syntax.

loadingVal <- matrix(0, 51, 7)

loadingVal[1:5, 1] <- c(1.1,0.2, 1.2,1.2,1.0)
loadingVal[6:11, 2] <- c(0.3,1, 0.9,0.1,0.8,0.6)
loadingVal[12:20, 3] <- c(0.5,0.5, 1.1,0.1,0.9,0.6,0.1,0.1,0.8)
loadingVal[21:30, 4] <- c(1.0,1.1,0.9,0.4,1.1,0.1,0.1,0.4,0.4,0.2)
loadingVal[31:37, 5] <- c(0.8,1.1, 0.5, 0.3,0.1,0.1,1.1)
loadingVal[38:41,6] <- c(1.2,0.7, 0.7,0.1)
loadingVal[42:51, 7] <- c(0.7,0.5, 0.9,0.6,0.2,0.1,1.1,0.6,0.7,0.8)

LY <- simsem::bind(loadingVal, "runif(1, 0.7, 1.2)")

factor.mean <- rep(NA, 7)
factor.mean.starting <- c(3,3,3,3,3,3,3)
AL <- simsem::bind(factor.mean, factor.mean.starting)

W <- matrix(NA, 7, 7)
W <- diag(c(0,0,0,0,0,0,0))
W[lower.tri(W)] <- c(1.1, 1.3, 1.0, 1.0, 0.9, 1.1,0.3, 0.1, 0, 0, 0,0,0, 0, 0, 0, 0, 0,0, 0, 0)
BE <- simsem::bind(W )

RPS <-simsem::bind(diag(7),symmetric = TRUE)

RTE <-simsem::bind(diag(51),symmetric = TRUE)

SEM.Model <- simsem::model(LY=LY, BE=BE, PS=RPS, TE=RTE, AL= AL ,modelType="SEM")
data_P <- simsem::generate(SEM.Model, 6000)
write.table(data_P, file="data_P.txt", quote=F)

But this new model has moderating moderation and also categorical variables. The categorical variables are income and education with three values each: low, medium and high.

Thanks in advance.
Regards,
Diya

**Comment by dgroy81** [comment]
This is a piece of code for a similar case. Is it okay?

dataSem <- '
BE=~0.95*BE1+0.955*BE2+0.95*BE3+0.8*BE4+0.9*BE5
BA=~0.1*BA1+.95*BA2+0.9*BA3+0.1*BA4+0.95*BA5+0.8*BA6
BAS=~0.1*BAS1+0.95*BAS2+0.9*BAS3+0.1*BAS4+0.95*BAS5+0.98*BAS6+0.1*BAS7+0.86*BAS9
PQ=~0.977*PQ1+0.985*PQ2+0.959*PQ3+0.1*PQ4+0.987*PQ5+0.2*PQ6+0.1*PQ7+0.15*PQ8+0.05*PQ9+0.09*PQ10
L=~0.988*L1+0.99*L2+0.1*L3+0.1*L4+0.1*L5+0.1*L6+0.96*L7
INF=~0.99*INF1+0.989*INF2+0.87*INF3+0.8*INF4
C=~0.8*C1+0.1*C2+0.8*C3+0.8*C4+0.1*C5+0.1*C6+0.9*C7+0.9*C8+0.9*C9+0.9*C10

INFEDINC=~INF+ED+INC+INF:ED+INF:INC
CEDINC=~C+ED+INC+C:ED+C:INC
PQCI=~PQ+C+INF+PQ:C+PQ:INF+INFEDINC+CEDINC
BE=~NA*BA+a*PQCI+b*BAS+c*L
a+b+c ==2.5
'


If I want to add constraints to make INC and ED within the rage of 1 to 3
and rests in the range of 1 to 5 , how to do it?

**Comment by TDJorgensen** [comment]
I responded to your lavaan-group post here:
https://groups.google.com/d/msg/lavaan/tXLtsqAXPZo/DzSCsnsVBQAJ
