### ISSUE TITLE
Help: Calculate sample size for an indirect effect

### ISSUE THREAD

**Issue by b1azk0** [simsem/simsem#55]
Hello,
I'm somehow new to the subject of running simulations and would very much appreciate some help in sorting out how to set up code for estimating sample size to observe an indirect effect in a setup like this:
![image](https://user-images.githubusercontent.com/22635132/51598061-058a0000-1efd-11e9-94b7-f7722cab2cb3.png)
Values represent typical effect sizes observed in previous research.
All scales (X1, X2, M, Y) have a reliability index Cronbachs alpha 0.85 to 0.95 depending on study.

Exemplary lavaan syntax to fit this model is this:
```
sem <- '
X1 =~ xv1 + xv2 + xv3 + xv4 + xv5
X2 =~ xxv1 + xxv2 + xxv3 + xxv4
M =~ m1 + m2 + m3 + m4
Y =~ y1 + y2
X1~~X2
# direct
# direct effect1
Y ~ c1 * X1
Y ~ c2 * X2
# mediator
M ~  a1 * X1
M ~ a2 * X2
Y ~ b * M
Direct_X1 := c1
Indirect_X1 := a1 * b
Total_X1 := c1 + (a1 * b)
Direct_X2 := c2
Indirect_X2 := a2 * b
Total_X2 := c2 + (a2 * b)
'
```
What I'm interested in is a sample size do detect an indirect effect of X1 with 80% power (in similar studies with composite measures the IE has a beta of 0.25; 95%CI (0.19; 0.31).

Could anyone please help me out?

I'd preferably use the simsem matrix approach as it seems to me I can learn from it the most

**Comment by b1azk0** [comment]
Thank you very, very much for this reply!
I think I'm able to create a data-generation model by inputting values to all parameters. Just to be sure:

1. when building latent factors I planned using values from multiple previous research - for instance I know that the X1 scale reliability was alpha=0.92 with 5 items. Using this knowledge shall I set all factor ladings to 0.9 or use some sort of range and draw model values from a uniform or normal distribution? What about residual variances for items? I could use standard deviation of those scores from previous studies, but maybe there is some other recognized way of doing this?

2. When defining latent factors variance, regression and covariance estimates should I think of standardized or unstandardized values? For example betas in regression paths, r correlation in covariance paths?

I know that those are not software only related questions - rather theoretical ones, but maybe I could get some guidance with this as well.

Anything actionable is much appreciated. Thank you once again

**Comment by TDJorgensen** [comment]
1. Coefficient alpha is influenced by the number of items.  See the `loadingFromAlpha()` function in the `semTools` package.
2. Only unstandardized parameters are model parameters. Standardized parameters are post-hoc transformations used as effect-size measures.  For Monte Carlo studies, common practice is to choose parameters that make a variable's total variance = 1, but it is not necessary.  If that is what you want, you can use the `RPS=` and `RTE=` arguments in `model()` to get simsem to calculate the corresponding unstandardized parameters for you.

**Comment by b1azk0** [comment]
I really appreciate your help with this. Thank you!
`loadingFromAlpha()` is a neat function... Do you know any similar functions that can help me with extracting all those: `LY`, `RPS`, `RTE` and other matrices from a model that I actually could have made on pilot data? If I can see those on my real life example I'm sure I can modify them further to generate proper samples and base my simulation on those.
I'm sure there is a general way (like `vartable()`) of getting those numbers, but maybe there's also some kind of a shortcut to get same numbers grouped in LISREL naming scheme (LY, RPS etc)

Now I tend to think that this would be the best approach and would definitely comfort all future reviewers...

**Comment by TDJorgensen** [comment]
You could just look at your actual `standardizedSolution()` and use those values as guidelines for your population parameters.  If you had correlated residuals (which you don't, but for anybody reading this in the future), you should set `cov.std=FALSE` to get "standardized" residual covariances that correspond to actual model parameters when the total variances == 1 for each variable.

**Comment by b1azk0** [comment]
isn't `inspect(fit, what = "est")` giving me actual matrices?
```
> inspect(semfit1, what = "est")
$lambda
        CN    IS   HAB    IH
cn1  1.288 0.000 0.000 0.000
cn2  1.245 0.000 0.000 0.000
cn3  1.174 0.000 0.000 0.000
cn4  1.166 0.000 0.000 0.000
cn5  1.198 0.000 0.000 0.000
is1  0.000 1.168 0.000 0.000
is2  0.000 1.136 0.000 0.000
is3  0.000 0.974 0.000 0.000
is4  0.000 1.150 0.000 0.000
hab1 0.000 0.000 1.123 0.000
hab2 0.000 0.000 1.019 0.000
hab3 0.000 0.000 1.049 0.000
hab4 0.000 0.000 1.128 0.000
ih1  0.000 0.000 0.000 0.922
ih2  0.000 0.000 0.000 0.893

$theta
     cn1   cn2   cn3   cn4   cn5   is1   is2   is3   is4   hab1  hab2  hab3  hab4  ih1   ih2  
cn1  0.683                                                                                    
cn2  0.000 0.808                                                                              
cn3  0.000 0.000 0.709                                                                        
cn4  0.000 0.000 0.000 0.662                                                                  
cn5  0.000 0.000 0.000 0.000 0.721                                                            
is1  0.000 0.000 0.000 0.000 0.000 0.271                                                      
is2  0.000 0.000 0.000 0.000 0.000 0.000 0.306                                                
is3  0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.527                                          
is4  0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.287                                    
hab1 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.721                              
hab2 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.727                        
hab3 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.545                  
hab4 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.561            
ih1  0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.569      
ih2  0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.958

$psi
    CN    IS    HAB   IH   
CN  1.000                  
IS  0.742 1.000            
HAB 0.000 0.000 1.000      
IH  0.000 0.000 0.000 1.000

$beta
        CN     IS   HAB IH
CN   0.000  0.000 0.000  0
IS   0.000  0.000 0.000  0
HAB  0.865 -0.292 0.000  0
IH  -0.226  0.027 0.869  0
```
These values come from a pilot study. If I replace non zero values with my own estimates, or better - estimates drawn from ranges of values - that would be the way to proceed, right?

**Comment by TDJorgensen** [comment]
> isn't `inspect(fit, what = "est")` giving me actual matrices?

Yes, and you can get the standardized values in matrices too:  `inspect(fit, what = "std")`

> If I replace non zero values with my own estimates, or better - estimates drawn from ranges of values - 

You mean parameters?  (population values for generating data)

> that would be the way to proceed, right?

Yes, that's efficient, and replacing them with distributions (random parameters) will make your result more generalizable.

**Comment by b1azk0** [comment]
Great - thank you very much!

**Comment by isaactpetersen** [comment]
How can we extend Example 17 (https://github.com/simsem/simsem/wiki/Example-17:-Select-a-set-of-variables-for-analysis) from the simsem documentation to test power to detect of the indirect effect from F11 to F33 via F22?

**Comment by TDJorgensen** [comment]
This is a closed issue, and off-topic.  Please post a new issue when you have one.

You can extend Example 17 using the `outfun=` argument to pass a custom function that returns (e.g.) the *p* value for the indirect effect in each replication.  This requires you to label the free parameters and calculate the indirect effect using lavaan model syntax to specify a user-defined parameter.  See this version of the example:

https://github.com/simsem/simsem/blob/master/SupportingDocs/Examples/Version05/ex17/ex17.R

```popModel <- "
f1 =~ 1*y1 + 1*y2 + 1*y3 + con1*y2 + con2*y3
f2 =~ 1*y4 + 1*y5 + 1*y6 + con3*y5 + con4*y6
f3 =~ 1*y7 + 1*y8 + 1*y9 + con5*y8 + con6*y9
f4 =~ 1*y10 + 1*y11 + 1*y12 + con1*y11 + con2*y12
f5 =~ 1*y13 + 1*y14 + 1*y15 + con3*y14 + con4*y15
f6 =~ 1*y16 + 1*y17 + 1*y18 + con5*y17 + con6*y18
f7 =~ 1*y19 + 1*y20 + 1*y21 + con1*y20 + con2*y21
f8 =~ 1*y22 + 1*y23 + 1*y24 + con3*y23 + con4*y24
f9 =~ 1*y25 + 1*y26 + 1*y27 + con5*y26 + con6*y27
f4 ~ 0.6*f1 + con7*f1
f5 ~ start(0.3)*f1 + 0.6*f2 + con8*f1 + con9*f2
f6 ~ start(0.3)*f2 + 0.6*f3 + con10*f2 + con11*f3
f7 ~ 0.6*f4 + con7*f4
f8 ~ start(0.3)*f4 + 0.6*f5 + con8*f4 + con9*f5
f9 ~ start(0.3)*f5 + 0.6*f6 + con10*f5 + con11*f6
f1 ~~ 1*f1
f2 ~~ 1*f2
f3 ~~ 1*f3
f4 ~~ 0.6*f4 + con12*f4
f5 ~~ 0.6*f5 + con13*f5
f6 ~~ 0.6*f6 + con14*f6
f7 ~~ 0.6*f7 + con12*f7
f8 ~~ 0.6*f8 + con13*f8
f9 ~~ 0.6*f9 + con14*f9
f1 ~~ 0.4*f2
f1 ~~ 0.4*f3
f2 ~~ 0.4*f3
y1 ~~ 0.5*y1
y2 ~~ 0.5*y2
y3 ~~ 0.5*y3
y4 ~~ 0.5*y4
y5 ~~ 0.5*y5
y6 ~~ 0.5*y6
y7 ~~ 0.5*y7
y8 ~~ 0.5*y8
y9 ~~ 0.5*y9
y10 ~~ 0.5*y10
y11 ~~ 0.5*y11
y12 ~~ 0.5*y12
y13 ~~ 0.5*y13
y14 ~~ 0.5*y14
y15 ~~ 0.5*y15
y16 ~~ 0.5*y16
y17 ~~ 0.5*y17
y18 ~~ 0.5*y18
y19 ~~ 0.5*y19
y20 ~~ 0.5*y20
y21 ~~ 0.5*y21
y22 ~~ 0.5*y22
y23 ~~ 0.5*y23
y24 ~~ 0.5*y24
y25 ~~ 0.5*y25
y26 ~~ 0.5*y26
y27 ~~ 0.5*y27
y1 ~~ 0.2*y10
y2 ~~ 0.2*y11
y3 ~~ 0.2*y12
y4 ~~ 0.2*y13
y5 ~~ 0.2*y14
y6 ~~ 0.2*y15
y7 ~~ 0.2*y16
y8 ~~ 0.2*y17
y9 ~~ 0.2*y18
y10 ~~ 0.2*y19
y11 ~~ 0.2*y20
y12 ~~ 0.2*y21
y13 ~~ 0.2*y22
y14 ~~ 0.2*y23
y15 ~~ 0.2*y24
y16 ~~ 0.2*y25
y17 ~~ 0.2*y26
y18 ~~ 0.2*y27
y1 ~~ 0.04*y19
y2 ~~ 0.04*y20
y3 ~~ 0.04*y21
y4 ~~ 0.04*y22
y5 ~~ 0.04*y23
y6 ~~ 0.04*y24
y7 ~~ 0.04*y25
y8 ~~ 0.04*y26
y9 ~~ 0.04*y27
med := con8 * con10  # INDIRECT EFFECT IN THE POPULATION (needed to calculate bias in results)
"

analyzeModel1 <- "
f1 =~ 1*y1 + con1*y2 + con2*y3
f2 =~ 1*y4 + con3*y5 + con4*y6
f3 =~ 1*y7 + con5*y8 + con6*y9
f4 =~ 1*y10 + con1*y11 + con2*y12
f5 =~ 1*y13 + con3*y14 + con4*y15
f6 =~ 1*y16 + con5*y17 + con6*y18
f7 =~ 1*y19 + con1*y20 + con2*y21
f8 =~ 1*y22 + con3*y23 + con4*y24
f9 =~ 1*y25 + con5*y26 + con6*y27
f4 ~ con7*f1
f5 ~ con8*f1 + con9*f2
f6 ~ con10*f2 + con11*f3
f7 ~ con7*f4
f8 ~ con8*f4 + con9*f5
f9 ~ con10*f5 + con11*f6
f1 ~~ f1
f2 ~~ f2
f3 ~~ f3
f4 ~~ con12*f4
f5 ~~ con13*f5
f6 ~~ con14*f6
f7 ~~ con12*f7
f8 ~~ con13*f8
f9 ~~ con14*f9
f1 ~~ f2
f1 ~~ f3
f2 ~~ f3
y1 ~~ y1
y2 ~~ y2
y3 ~~ y3
y4 ~~ y4
y5 ~~ y5
y6 ~~ y6
y7 ~~ y7
y8 ~~ y8
y9 ~~ y9
y10 ~~ y10
y11 ~~ y11
y12 ~~ y12
y13 ~~ y13
y14 ~~ y14
y15 ~~ y15
y16 ~~ y16
y17 ~~ y17
y18 ~~ y18
y19 ~~ y19
y20 ~~ y20
y21 ~~ y21
y22 ~~ y22
y23 ~~ y23
y24 ~~ y24
y25 ~~ y25
y26 ~~ y26
y27 ~~ y27
y1 ~~ y10
y2 ~~ y11
y3 ~~ y12
y4 ~~ y13
y5 ~~ y14
y6 ~~ y15
y7 ~~ y16
y8 ~~ y17
y9 ~~ y18
y10 ~~ y19
y11 ~~ y20
y12 ~~ y21
y13 ~~ y22
y14 ~~ y23
y15 ~~ y24
y16 ~~ y25
y17 ~~ y26
y18 ~~ y27
y1 ~~ y19
y2 ~~ y20
y3 ~~ y21
y4 ~~ y22
y5 ~~ y23
y6 ~~ y24
y7 ~~ y25
y8 ~~ y26
y9 ~~ y27
med := con8 * con10 # ESTIMATED INDIRECT EFFECT
"

## custom function to return p value
getPval <- function(fit) {
  PE <- parameterEstimates(fit)
  PE$pvalue[PE$op == ":="]
}

## run 10 replications for a quick example
Output1 <- sim(10, n=200, analyzeModel1, generate=popModel,
              lavaanfun="lavaan", outfun = getPval)

## list of resulting p values
getExtraOutput(Output1)

## concatenate into a vector, calculate mean of rejections at alpha = .05 (i.e., power)
mean(do.call(c, getExtraOutput(Output1)) < .05)
```

**Comment by isaactpetersen** [comment]
Thanks, and sorry for posting on a closed issue.  I'll open a new issue.
