### ISSUE TITLE
covariance matrix of latent variables is not positive definite

### ISSUE THREAD

**Issue by N34980** [simsem/simsem#60]
Hi,

First of all, many thanks for developing this package! 

I am actually trying to do a power analysis for a CFA and I am struggling a bit. When I run the code below, I get a message warning me that the matrix of latent variables is not positive definite... However, when I use lavInspect(out, "cov.lv"), I can't see anything wrong. Would you have any idea of what may cause this message? Is it that the parameters I am specifying are not compatible between them (can't run the model)? Or that I mis-wrote something? Any help would be much appreciated!

Roger

library(lavaan)
library(simsem)

# 9 Factors and 33 loadings in total
loading <- matrix(0, 33, 9)
loading[1:3, 1] <- NA
loading[4:7, 2] <- NA
loading[8:11, 3] <- NA
loading[12:15, 4] <- NA
loading[16:18, 5] <- NA
loading[19:21, 6] <- NA
loading[22:25, 7] <- NA
loading[26:30, 8] <- NA
loading[31:33, 9] <- NA
loadingValues <- matrix(0, 33, 9)
loadingValues[1:3, 1] <- 0.8
loadingValues[4:7, 2] <- 0.7
loadingValues[8:11, 3] <- 0.7
loadingValues[12:15, 4] <- 0.7
loadingValues[16:18, 5] <- 0.7
loadingValues[19:21, 6] <- 0.8
loadingValues[22:25, 7] <- 0.7
loadingValues[26:30, 8] <- 0.7
loadingValues[31:33, 9] <- 0.7
LY <- bind(loading, loadingValues)

# No error correlation
error.cor <- matrix(0, 33, 33)
diag(error.cor) <- 1
RTE <- binds(error.cor)

# As Factor variance is set to 1 and this is a CFA, error variance should be set to 1 minus squaredLoadings
error.var <- rep(NA, 33)
error.varValues <-c(rep(0.36,3),rep(0.51,15),rep(0.36,3),rep(0.51,12))
VTE <- bind(error.var, error.varValues)  

# Factor variances are set to 1. Hence, correlations are specified in the Matrix
facCov <- matrix(NA, 9, 9)
facCovVal <- diag(c(1,1,1,1,1,1,1,1,1))
facCovVal[lower.tri(facCovVal)] <- c(0.5,0.5,0.1,0.3,0.3,0.1,0.4,0.5,0.0,0.5,0.3,0.3,-0.3,0.4,0.5,0.5,0.3,0.3,0.1,0.4,0.5,0.2,0.2,-0.3,0.4,0.5,0.6,0.1,0.4,0.3,0.0,0.6,0.3,-0.1,-0.1,0.3)
facCovVal[upper.tri(facCovVal)] <- c(0.5,0.5,0.0,0.1,0.5,0.5,0.3,0.3,0.3,0.2,0.3,0.3,0.3,0.2,0.6,0.1,-0.3,0.1,-0.3,0.1,0.0,0.4,0.4,0.4,0.4,0.4,0.6,-0.1,0.5,0.5,0.5,0.5,0.3,0.3,-0.1,0.3)
RPS <- binds(facCov, facCovVal)

CFA.Model <- model(LY = LY, RPS = RPS, RTE = RTE, modelType="CFA")

summary(CFA.Model)

dat <- generate(CFA.Model, 200)
out <- analyze(CFA.Model, dat)

**Comment by TDJorgensen** [comment]
When you paste syntax, make sure to wrap it up in 3 backticks (`) above and below so that your comments are not interpreted as Markdown headings.
https://guides.github.com/features/mastering-markdown/

> when I use lavInspect(out, "cov.lv"), I can't see anything wrong

There is not a Heywood case, but it is still NPD.  Check the determinant (which is negative) or eigenvalues (the last is negative).
```
det(lavInspect(out, "cov.lv"))
eigen(lavInspect(out, "cov.lv"))$values
```

> Is it that the parameters I am specifying are not compatible between them (can't run the model)? 

The model runs fine (see `summary(out)` output). Your population Psi is positive definite:
```
eigen(facCovVal)$values # all positive
```
But the last eigen value is pretty small.  So you can expect Psi estimates to be NPD in finite samples just due to sampling error (i.e., more often NPD in smaller samples, especially when your model estimates so many parameters (133) relative to your sample size). It is nothing to worry about. Unconstrained estimation allows for theoretically impossible estimates, but we must not make the mistake of reifying estimates (they are not parameters, they are merely estimates of parameters).

**Comment by N34980** [comment]
Hi Terence,
Many (MANY) thanks for your response! It is my first time on Github so thanks for the ''' tip too.
I actually specified my correlations wrongly with the simsem syntax... so I corrected them. Now it runs fine. I actually had a hard time trying to translate the Lavaan syntax, which I am more used to, into the simsem syntax. To check that I was doing the right things, I tried to re-run my model using both the simsem and the Lavaan syntax, but while the simsem syntax runs, using the Lavaan syntax results in an error "Error in clean(simResult) : All replications in the result object are not convergent. Thus, the result object cannot be used"
As I am a bit lost, could you please let me know if you think the two syntaxes are actually identical? And if not where the problem might be?
Also, as I expect data to be collected to be skewed, I used the indDist argument in conjunction with the MLR estimator. Did I do this the right way?
Finally, F2 ~~ F4 (correlation of -0.3) seems to be detected as significant at n = 88. However, F2 ~~ F3 and F2 ~~ F5 (correlation of +0.3) seem to be detected as significant at n = 160+. While the absolute values of these correlations are the same, the sample size required for F2 ~~ F4 is half of the sample sizes required for F2 ~~ F3 and F2 ~~ F5... Is this theoretically explainable?
I am apologising for the lengthy thread... Trying to get my head around simsem and sample size planning.

The SimSem syntax:
```# 9 Factor and 33 loadings in total
loading <- matrix(0, 33, 9)
loading[1:3, 1] <- NA
loading[4:7, 2] <- NA
loading[8:11, 3] <- NA
loading[12:15, 4] <- NA
loading[16:18, 5] <- NA
loading[19:21, 6] <- NA
loading[22:25, 7] <- NA
loading[26:30, 8] <- NA
loading[31:33, 9] <- NA
loadingValues <- matrix(0, 33, 9)
loadingValues[1:3, 1] <- 0.8
loadingValues[4:7, 2] <- 0.7
loadingValues[8:11, 3] <- 0.7
loadingValues[12:15, 4] <- 0.7
loadingValues[16:18, 5] <- 0.7
loadingValues[19:21, 6] <- 0.8
loadingValues[22:25, 7] <- 0.7
loadingValues[26:30, 8] <- 0.7
loadingValues[31:33, 9] <- 0.7

LY <- bind(loading, loadingValues)

# No error correlation
error.cor <- matrix(0, 33, 33)
diag(error.cor) <- 1
RTE <- binds(error.cor)

# As Factor variance is set to 1 and this is a CFA, error variance should be set to 1 minus squaredLoadings
error.var <- rep(NA, 33)
error.varValues <-c(rep(0.36,3),rep(0.51,15),rep(0.36,3),rep(0.51,12))
VTE <- bind(error.var, error.varValues)  

# Factor variance set to 1. Hence, correlations are specified in the Matrix
facCov <- matrix(NA, 9, 9)
facCovVal <- diag(c(1,1,1,1,1,1,1,1,1))

facCovVal[lower.tri(facCovVal)] <- c(0.5,0.3,0.1,0.3,0.5,0.1,0.4,0.5,0.3,-0.3,0.3,0.0,0.5,0.4,0.5,0.1,0.6,0.3,0.2,0.4,0.3,0.0,0.1,-0.3,-0.1,-0.1,0.3,0.2,0.6,0.3,0.5,0.4,0.5,0.4,0.5,0.3)
facCovVal[upper.tri(facCovVal)] <- c(0.5,0.3,0.3,0.1,-0.3,0.1,0.3,0.3,0.6,0.0,0.5,0.0,0.3,0.1,0.3,0.1,0.5,0.2,-0.3,0.2,0.5,0.4,0.4,0.4,-0.1,0.6,0.4,0.4,0.5,0.5,0.3,-0.1,0.3,0.5,0.5,0.3)
RPS <- binds(facCov, facCovVal)

CFA.Model <- model(LY = LY, RPS = RPS, RTE = RTE, modelType="CFA")

dist<-bindDist(p=33, skewness=1.5, kurtosis=3.0)
 
analysis<-sim(nRep = NULL, n = rep(seq(50,1000,100),50), CFA.Model, multicore=TRUE, indDist=dist, estimator="mlr", seed=0)
power <- getPower(analysis)
findPower(power, "N", 0.80)
```
Everything runs fine

The Lavaan syntax
```analysisModel <-'
 #Loadings
 F1 =~ ind1 + ind2 + ind3
 F2 =~ ind4 + ind5 + ind6 + ind7
 F3 =~ ind8 + ind9 + ind10 + ind11
 F4 =~ ind12 + ind13 + ind14 + ind15
 F5 =~ ind16 + ind17 + ind18
 F6 =~ ind19 + ind20 + ind21
 F7 =~ ind22 + ind23 + ind24 + ind25
 F8 =~ ind26 + ind27 + ind28 + ind29 + ind30
 F9 =~ ind31 + ind32 + ind33
 
 # residuals
 ind1~~ind1
 ind2~~ind2
 ind3~~ind3
 ind4~~ind4
 ind5~~ind5
 ind6~~ind6
 ind7~~ind7
 ind8~~ind8
 ind9~~ind9
 ind10~~ind10
 ind11~~ind11
 ind12~~ind12
 ind13~~ind13
 ind14~~ind14
 ind15~~ind15
 ind16~~ind16
 ind17~~ind17
 ind18~~ind18
 ind19~~ind19
 ind20~~ind20
 ind21~~ind21
 ind22~~ind22
 ind23~~ind23
 ind24~~ind24
 ind25~~ind25
 ind26~~ind26
 ind27~~ind27
 ind28~~ind28
 ind29~~ind29
 ind30~~ind30
 ind31~~ind31
 ind32~~ind32
 ind33~~ind33

# Variances
 F1 ~~ F1
 F2 ~~ F2
 F3 ~~ F3
 F4 ~~ F4
 F5 ~~ F5
 F6 ~~ F6
 F7 ~~ F7
 F8 ~~ F8
 F9 ~~ F9

 
 ##Correlations to specify
 F1 ~~ F2 + F3 + F4 + F5 + F6 + F7 + F8 + F9
 F2 ~~ F3 + F4 + F5 + F6 + F7 + F8 + F9
 F3 ~~ F4 + F5 + F6 + F7 + F8 + F9
 F4 ~~ F5 + F6 + F7 + F8 + F9
 F5 ~~ F6 + F7 + F8 + F9
 F6 ~~ F7 + F8 + F9
 F7 ~~ F8 + F9
 F8 ~~ F9
 '

popModel <-'
 F1 =~ 0.8*ind1 + 0.8*ind2 + 0.8*ind3
 F2 =~ 0.7*ind4 + 0.7*ind5 + 0.7*ind6 + 0.7*ind7
 F3 =~ 0.7*ind8 + 0.7*ind9 + 0.7*ind10 + 0.7*ind11
 F4 =~ 0.7*ind12 + 0.7*ind13 + 0.7*ind14 + 0.7*ind15
 F5 =~ 0.7*ind16 + 0.7*ind17 + 0.7*ind18
 F6 =~ 0.8*ind19 + 0.8*ind20 + 0.8*ind21
 F7 =~ 0.7*ind22 + 0.7*ind23 + 0.7*ind24 + 0.7*ind25
 F8 =~ 0.7*ind26 + 0.7*ind27 + 0.7*ind28 + 0.7*ind29 + 0.7*ind30
 F9 =~ 0.7*ind31 + 0.7*ind32 + 0.7*ind33
 
 # residuals
 ind1~~0.36*ind1
 ind2~~0.36*ind2
 ind3~~0.36*ind3
 ind4~~0.51*ind4
 ind5~~0.51*ind5
 ind6~~0.51*ind6
 ind7~~0.51*ind7
 ind8~~0.51*ind8
 ind9~~0.51*ind9
 ind10~~0.51*ind10
 ind11~~0.51*ind11
 ind16~~0.51*ind16
 ind17~~0.51*ind17
 ind18~~0.51*ind18
 ind12~~0.51*ind12
 ind13~~0.51*ind13
 ind14~~0.51*ind14
 ind15~~0.51*ind15
 ind19~~0.36*ind19
 ind20~~0.36*ind20
 ind21~~0.36*ind21
 ind22~~0.51*ind22
 ind23~~0.51*ind23
 ind24~~0.51*ind24
 ind25~~0.51*ind25
 ind26~~0.51*ind26
 ind27~~0.51*ind27
 ind28~~0.51*ind28
 ind29~~0.51*ind29
 ind30~~0.51*ind30
 ind31~~0.51*ind31
 ind32~~0.51*ind32
 ind33~~0.51*ind33

 #Fixed variances
 F1 ~~ 1*F1
 F2 ~~ 1*F2
 F3 ~~ 1*F3
 F4 ~~ 1*F4
 F5 ~~ 1*F5
 F6 ~~ 1*F6
 F7 ~~ 1*F7
 F8 ~~ 1*F8
 F9 ~~ 1*F9

 
 #Correlations to specify
 F1 ~~ 0.5*F2 + 0.3*F3 + 0.1*F4 + 0.3*F5 + 0.5*F6 + 0.1*F7 + 0.4*F8 + 0.5*F9
 F2 ~~ 0.3*F3 + -0.3*F4 + 0.3*F5 + 0.0*F6 + 0.5*F7 + 0.4*F8 + 0.5*F9
 F3 ~~ 0.1*F4 + 0.6*F5 + 0.3*F6 + 0.2*F7 + 0.4*F8 + 0.3*F9
 F4 ~~ 0.0*F5 + 0.1*F6 + -0.3*F7 + -0.1*F8 + -0.1*F9
 F5 ~~ 0.3*F6 + 0.2*F7 + 0.6*F8 + 0.3*F9
 F6 ~~ 0.5*F7 + 0.4*F8 + 0.5*F9
 F7 ~~ 0.4*F8 + 0.5*F9
 F8 ~~ 0.3*F9
 '

analysis2<-sim(nRep = NULL, model=analysisModel, n = rep(seq(50,1000,100),50), generate=popModel, std.lv=TRUE, lavaanfun = "cfa", indDist=dist, multicore=TRUE, estimator="mlr")

power2 <- getPower(analysis2) # here I get the error
findPower(power2, "N", 0.80)
```

**Comment by TDJorgensen** [comment]
You can compare the population models in your output to see if they are the same model:
```
analysis@paramValue
analysis2@paramValue
```
Your use of `bindDist()` is fine if you want all variables to have the exact same skew/kurtosis.

**Comment by TDJorgensen** [comment]
> While the absolute values of these correlations are the same, the sample size required for F2 ~~ F4 is half of the sample sizes required for F2 ~~ F3 and F2 ~~ F5... Is this theoretically explainable?

It is counter-intuitive, but not necessarily wrong.  MANOVA has more power to detect group differences when 2 DVs are negatively correlated then when they are positively correlated.  Not sure if this is related.

Another issue is that Vale-Maurelli's power transformation (to make variables skewed/kurtotic) can change the expected covariance structure.  So pay attention to your parameter estimates, too.  Perhaps there is bias (and more so among some parameters than others) that affects the power for what you thought were identical absolute values.

**Comment by N34980** [comment]
Hi Terrence,

Thank you very much for your response! 

I carried out many different analyses and arrived to what I wanted (I think!). 
From what I can recall, the simsem and Lavaan syntaxes were not identical because the simsem syntax resulted in the estimation of intercepts (not estimated using the Lavaan syntax I used). 

When I estimated the Lavaan model for a specific N, I had to explicitly set the variances to 1 in the Lavaan syntax in order to get results satisfying parameter estimate bias >0.1, SE bias >0.1, Coverage >0.91, and Power >.80. My guess is that variances have to be set to 1 in both the analysis and population models when the lavaan function is used?

For information, the analysis for determining sample size was called by:
sim(nRep = NULL, model=analysisModel, n = rep(seq(100,1000,20),1000), generate=popModel, lavaanfun = "lavaan", meanstructure=FALSE, indDist=dist, estimator="mlr")
The analysis for a specific N was called by:
sim(nRep = 10000, model=analysisModel, n = N, generate=popModel, lavaanfun = "lavaan", meanstructure=FALSE, indDist=dist, estimator="mlr", seed=103)

With the analysis for a specific N, the number of converged replications was 9270/10000 (760 were non convergent due to NPD matrices issues). Would you trust the results of that analysis (is 100% convergence necessary for power analysis)? I mean, can I safely write that for that N, results satisfied parameter estimate bias >0.1, SE bias >0.1, Coverage >0.91, and Power >.80, although there were non-convergent replications?

RE the absolute correlation values... MANY thanks for the explanations!

**Comment by TDJorgensen** [comment]
As I mentioned before, Heywood cases are not a problem. The model can converge on solutions that are NPD. You know you are fitting the right model, so sampling error is the only reason for them.
