### ISSUE TITLE
How to simulate the Latent growth mixture model with 3-classes?

### ISSUE THREAD

**Issue by seonghobae** [simsem/simsem#61]
Hello,

How to simulate the Latent growth mixture model with 3-classes?
I tried to find out how to do that; however, I can not find out over 2-classes.
Can I see any examples of how to specification of three classes latent growth model?

Best,
Seongho

**Comment by TDJorgensen** [comment]
`lavaan` does not estimate any latent class models.  Perhaps `OpenMx` does, you can search their site for examples. 

If you are simulating data, the classes are not latent in the population model.  You can just simulate from a 3-group SEM.  See examples [here](https://github.com/simsem/simsem/blob/master/SupportingDocs/Examples/Version05/exMultipleFormat/multipleGroup.R).

**Comment by seonghobae** [comment]
Thanks for the quick response! Humm, I'm trying to fit LGMM with OpenMx and simsem right now.

**Comment by TDJorgensen** [comment]
OK, it looks like Sunthud (who is no longer active on this project) was experimenting with something back in 2014.  I have minimal familiarity with OpenMx, and none with mixture models, so I cannot provide any examples for you.  But judging from the script and the `?mxModel` help page, it would seem you can simply 

1. specify as many `subpop3`, `subpop4`, ... as you want, 
2. add those log-likelihoods to the `algObj <- mxAlgebra(...)` assignment, and
3. pass the additional `subpop3`, `subpop4`, ... to the `popModel <- mxModel( ...)` assignment.  Also remember to make the `n=` list as long as necessary to simulate correct sample sizes from each sub-population.

As I said, simsem is flexible enough to allow you to design and use any data-generating function, model-fitting function, and/or output-saving function via those arguments to `sim()`.  But it is up to the user to work out those details.

Good luck!
