### ISSUE TITLE
Error in rnorm(p * n) : invalid arguments

### ISSUE THREAD

**Issue by keithmarkus** [simsem/simsem#68]
I get the error in the subject line when running examples with a list of sample data sets.  Here is the "Getting Started" example with 10 reps.

varnames <- c("x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9")
cm <- cov(HolzingerSwineford1939[,varnames])
library(MASS)
dataList <- list()
for(i in 1:10) {
  dataList[[i]] <- mvrnorm(200, rep(0, 9), cm) 
}
analyzeModel <- "
    f1 =~ x1 + x2 + x3
    f2 =~ x4 + x5 + x6
    f3 =~ x7 + x8 + x9
"
Outputx <- sim(NULL, model = analyzeModel, rawData = dataList, lavaanfun = "cfa")
traceback()

And are the first few lines of the traceback:

6: rnorm(p * n)
5: matrix(rnorm(p * n), n)
4: MASS::mvrnorm(n = sample.nobs[g], mu = Mu.hat[[g]], Sigma = COV, 
       empirical = empirical)
3: (function (model = NULL, model.type = "sem", meanstructure = FALSE, 
       int.ov.free = TRUE, int.lv.free = FALSE, conditional.x = FALSE, 
       fixed.x = FALSE, orthogonal = FALSE, std.lv = TRUE, auto.fix.first = FALSE, 
       auto.fix.single = FALSE, auto.var = TRUE, auto.cov.lv.x = TRUE, 
       auto.cov.y = TRUE, ..., sample.nobs = 500L, ov.var = NULL, 
       group.label = paste("G", 1:ngroups, sep = ""), skewness = NULL, 
       kurtosis = NULL, seed = NULL, empirical = FALSE, return.type = "data.frame", 
       return.fit = FALSE, debug = FALSE, standardized = FALSE) 
...

And here is my sessionInfo:
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.7 LTS

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

Random number generation:
 RNG:     L'Ecuyer-CMRG 
 Normal:  Inversion 
 Sample:  Rejection 
 
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] MASS_7.3-53   simsem_0.5-15 lavaan_0.6-7 

loaded via a namespace (and not attached):
[1] compiler_4.0.3 parallel_4.0.3 tools_4.0.3    tinytex_0.25   tmvnsim_1.0-2  mnormt_2.0.2   pbivnorm_0.6.0 xfun_0.16     
[9] stats4_4.0.3  
> 

Keith Markus
kmarkus@aol.com

**Comment by TDJorgensen** [comment]
Hi Keith,

This is the last error I fixed, about a month ago.  You can install the latest development version (0.5-15.905) to verify that this example works now:
```
devtools::install_github("simsem/simsem/simsem")
```
I haven't made many updates since the last version went to CRAN in February, but perhaps I should go ahead and send this version.
