### ISSUE TITLE
Getting the raw data of a simulation study

### ISSUE THREAD

**Issue by Nikazahe** [simsem/simsem#72]
Hi 

Is there a way of getting the raw data of a simulated dataset? I simulated a dataset with the code below and would like to access each of the datasets so I can impose missing values on them. 

sim(1000, n=200, growth.Model, seed=751785)

Thanks a lot!

**Comment by TDJorgensen** [comment]
> Is there a way of getting the raw data of a simulated dataset?

You can use the `generate()` function directly, which is one of the steps called by `sim()`, so you should get the same data when using the same arguments.

```
set.seed(751785)
dat1 <- generate(model = growth.Model, n=200) # first rep
dat2 <- generate(model = growth.Model, n=200) # second rep
## or all reps:
set.seed(751785)
dataList <- lapply(1:1000, function(i) generate(model = growth.Model, n=200))
```

> I simulated a dataset with the code below and would like to access each of the datasets so I can impose missing values on them.

You can pass a missing-data template to the `miss=` argument, unless you just want to be able to visualize the missing data on a single data set.  I know that reassures me that everything is working as expected :-)

**Comment by schoam4** [comment]
I you want to generate the data in one step, look at it/manipulate it, then analyze it. You can use the dataOnly argument in the sim function to return a list of data frames, then when you want to analyze the data you can specify the list of data frames in rawData argument of the sim function. If all you want to do is look at a single data set then generate works well, but if you need to do some complex manipulation of the data (or if you want to fit several models to the same data) then the dataOnly argument is a nice option.
