### ISSUE TITLE
Bayesian estimation in Simsem?

### ISSUE THREAD

**Issue by Nikazahe** [simsem/simsem#73]
Hi 

I was wondering if a Bayesian estimation of Growth Curve Models is available in simsem. 

Thanks!

**Comment by TDJorgensen** [comment]
simsem does not provide any engines for analyzing data.  It merely uses existing engines, mostly the lavaan package and to a lesser degree the OpenMx package.  But you can write any custom data-analysis function you want (see the `?sim` help page; the last example provides a trivial case to show how it basically works).  You could write a function that utilizes the blavaan package, for example.
