### ISSUE TITLE
Reset random number generator to default after running sim()

### ISSUE THREAD

**Issue by isaactpetersen** [simsem/simsem#74]
I have run into reproducibility issues with other R code because the `sim()` command changes the random number generator from the R default ("Mersenne-Twister") to "L'Ecuyer-CMRG" (See https://github.com/simsem/simsem/blob/master/simsem/R/sim.R#L25 and https://github.com/simsem/simsem/blob/master/simsem/R/sim.R#L737) without changing it back to the default after running the simulation. To clarify, I'm fine with `{simsem}` using "L'Ecuyer-CMRG" for its random number generator, but it'd be nice for it to change it back to default (or whatever it was set to previously) after the simulation is completed, so that it plays well with other R code for reproducibility's sake. Otherwise, the answer you get to a piece of code could differ depending on whether you run the code before or after running `sim()`.

**Comment by TDJorgensen** [comment]
I am limited by the R Core Team's rejection of packages that overwrite global variables such as `.Random.seed`.  But I'm not sure how simsem changing the RNG type is a problem.  Even if the RNG type remained the twister, the `seed=` argument gets set by `sim()`, so whatever the `.Random.seed` was before is written over.  Assuming the `.Random.seed` was under your control prior to running `sim()`, you can set it again using `set.seed(seed, kind = "Mersenne-Twister")` to reproduce whatever results you achieved previously.

**Comment by isaactpetersen** [comment]
Yes, it's true that the user can manually specify the RNG type after re-running `sim()`. However, the user may not realize that `sim()` changes the RNG type, which poses challenges to reproducibility. It took me some time to troubleshoot why I was getting different random numbers before and after running `sim()` even though the seed was the same. It might be worth re-setting the RNG type to the previous RNG type so that the random numbers generated before and after running `sim()` are the same. Here's a minimal reproducible example:

```
#Libraries
library("simsem")

# Generate random numbers
set.seed(12345)
rnorm(5)

# Run sim()
popModel <- "
f1 =~ 0.7*y1 + 0.7*y2 + 0.7*y3
f2 =~ 0.7*y4 + 0.7*y5 + 0.7*y6
f1 ~~ 1*f1
f2 ~~ 1*f2
f1 ~~ 0.5*f2
y1 ~~ 0.49*y1
y2 ~~ 0.49*y2
y3 ~~ 0.49*y3
y4 ~~ 0.49*y4
y5 ~~ 0.49*y5
y6 ~~ 0.49*y6
"

analysisModel <- "
f1 =~ y1 + y2 + y3
f2 =~ y4 + y5 + y6
"

Output <- sim(5,
              model = analysisModel,
              n = 200,
              generate = popModel,
              std.lv = TRUE,
              lavaanfun = "cfa")

# Generate random numbers (this yields different numbers than above despite the same seed)
set.seed(12345)
rnorm(5)
```

**Comment by TDJorgensen** [comment]
> the user may not realize that `sim()` changes the RNG type

True, I was under the impression that Sunthud had programmed a message to bring this to the user's attention, but I must have been thinking of what I programmed in `semTools::permuteMeasEq` and parcel-allocation functions that allow using the `parallel` package.

Where `sim()` changes the `RNGkind()`, I have updated the source code to conditionally print a message giving the user instructions about returning to the previous `RNGkind()`.

```
if (RNGkind()[1L] != "L'Ecuyer-CMRG") {
    message('The RNGkind() was changed from "', RNGkind()[1L],
            '" to RNGkind("L\'Ecuyer-CMRG") in order to enable the multiple ',
            'streams in the parallel package.\nTo set a RNG seed using the ',
            'previous RNGkind(), you can use\n\tRNGkind("',
            paste(RNGkind(), collapse = '","'), '")\n or \n\t',
            'set.seed(seed, kind = "', RNGkind()[1L], '")')
    RNGkind("L'Ecuyer-CMRG")
}
```

Which looks more legibly like this at the Console:

```
The RNGkind() was changed from "Mersenne-Twister" to RNGkind("L'Ecuyer-CMRG") in order to enable the multiple streams in the parallel package.
To set a RNG seed using the previous RNGkind(), you can use
	RNGkind("Mersenne-Twister","Inversion","Rejection")
 or 
	set.seed(seed, kind = "Mersenne-Twister")
```

**Comment by TDJorgensen** [comment]
Oh, and to install the development version to try this:
```
devtools::install_github("simsem/simsem/simsem")
```
