### ISSUE TITLE
Warning message: The sample size argument 'n' is suppressed when 'rawData' is specified.

### ISSUE THREAD

**Issue by bugiu** [simsem/simsem#79]
Hi!
I do have an issue in running my simulation to detect the sample size for a model I want to test, but I got this error message: Error in sim(NULL, model = analysis.mod1, n = list(500, 500), rawData = popData, : Check the list object specified in the 'rawData' argument; list must either contain matrices or data frames In addition: Warning message: In sim(NULL, model = analysis.mod1, n = list(500, 500), rawData = popData, : The sample size argument 'n' is suppressed when 'rawData' is specified.
I am sure about how to write the analysis mod. Plus, not sure if I have to run the simulation for the 4 types of invariances (noninvariance, configural, weak and strong). Finally I dnk if the control variables are specified correctly. Can you help me out?

#impute control variables 
gender <- rep(c(0,1), 800)
age <- rep (18:80, 25)
fs <-rep(c(0,1), 800)
ed <- rep(1:7, 200)
nationality <- rep(c(0,1), 800)
income <- rep(1:10, 160)

#run pop model with 6 covariates included  
#modpopa

popModela <- `
#measurament model
sti =~ 0.70*s1 + 0.70*s2 + 0.70*s3
pc =~ 0.70*p1 + 0.70*p2 + 0.70*p3
ic =~ 0.70*i1 + 0.70*i2 + 0.70*i3
att =~ 0.70*a1 + 0.70*a2 + 0.70*a3
sn =~ 0.70*sn1 + 0.70*sn2 + 0.70*sn3
pbc =~ 0.70*pb1 + 0.70*pb2 + 0.70*pb3 + 0.70*pb4
int =~ 0.70*in1 + 0.70*in2 + 0.70*in3
pb =~ 0.70*pb1

pb~~ 1*pb                
sti ~~ 1*sti
pc ~~ 1*pc
ic ~~ 1*ic
att  ~~ 1*att
sn ~~ 1*sn
pbc ~~ 1*pbc
int ~~ 1*int
 
sti  ~~ 0.5*pc
sti ~~ 0.5*ic
sti ~~ 0.5*att
sti ~~ 0.5*sn
sti ~~ 0.5*pbc
sti ~~ 0.5*int
sti ~~ 0.5*pb
pc ~~ 0.5*ic
pc ~~ 0.5*att
pc ~~ 0.5*sn
pc ~~ 0.5*pbc
pc ~~ 0.5*int
ic ~~ 0.5*att
ic ~~ 0.5*sn
ic ~~ 0.5*pbc
ic ~~ 0.5*int
ic ~~ 0.5*pb
att ~~ 0.5*sn
att ~~ 0.5*pbc
att ~~ 0.5*int
att ~~ 0.5*pb
sn ~~ 0.5*pbc
sn ~~ 0.5*int
sn ~~ 0.5*pb
pbc ~~ 0.5*int
pbc ~~ 0.5*pb
int ~~ 0.5*pb

s1 ~~ 0.49*s1
s2 ~~ 0.49*s2
s3 ~~ 0.49*s3
p1 ~~ 0.49*p1
p2 ~~ 0.49*p2
p3 ~~ 0.49*p3
i1 ~~ 0.49*i1
i2 ~~ 0.49*i2
i3 ~~ 0.49*i3
a1 ~~ 0.49*a1
a2 ~~ 0.49*a2
a3 ~~ 0.49*a3
sn1 ~~ 0.49*sn1
sn2 ~~ 0.49*sn2
sn3 ~~ 0.49*sn3
pbc1 ~~ 0.49*pbc1
pbc2 ~~ 0.49*pbc2
pbc3 ~~ 0.49*pbc3
pbc4  ~~ 0.49*pbc4
in1~~ 0.49*in1
in2~~ 0.49*in2
in3~~ 0.49*in3
pb1 ~~ 1*pb1

#structural model

att ~ -0.50*sti  + 0.50*pc + 0.50*ic
int ~ 0.50*att + 0.50*sn + 0.50*pbc + 0.50*pb + 0.5*gender + 0.5*age + 0.5*fs +0.5*nationality + 0.5*income `

#popmodb
popModelb <- `
#measurament model
sti =~ 0.70*s1 + 0.70*s2 + 0.70*s3
pc =~ 0.70*p1 + 0.70*p2 + 0.70*p3
ic =~ 0.70*i1 + 0.70*i2 + 0.70*i3
att =~ 0.70*a1 + 0.70*a2 + 0.70*a3
sn =~ 0.70*sn1 + 0.70*sn2 + 0.70*sn3
pbc =~ 0.70*pb1 + 0.70*pb2 + 0.70*pb3 + 0.70*pb4
int =~ 0.70*in1 + 0.70*in2 + 0.70*in3
pb =~ 0.70*pb1

pb~~ 1*pb                
sti ~~ 1*sti
pc ~~ 1*pc
ic ~~ 1*ic
att  ~~ 1*att
sn ~~ 1*sn
pbc ~~ 1*pbc
int ~~ 1*int
 
sti  ~~ 0.5*pc
sti ~~ 0.5*ic
sti ~~ 0.5*att
sti ~~ 0.5*sn
sti ~~ 0.5*pbc
sti ~~ 0.5*int
sti ~~ 0.5*pb
pc ~~ 0.5*ic
pc ~~ 0.5*att
pc ~~ 0.5*sn
pc ~~ 0.5*pbc
pc ~~ 0.5*int
ic ~~ 0.5*att
ic ~~ 0.5*sn
ic ~~ 0.5*pbc
ic ~~ 0.5*int
ic ~~ 0.5*pb
att ~~ 0.5*sn
att ~~ 0.5*pbc
att ~~ 0.5*int
att ~~ 0.5*pb
sn ~~ 0.5*pbc
sn ~~ 0.5*int
sn ~~ 0.5*pb
pbc ~~ 0.5*int
pbc ~~ 0.5*pb
int ~~ 0.5*pb

s1 ~~ 0.49*s1
s2 ~~ 0.49*s2
s3 ~~ 0.49*s3
p1 ~~ 0.49*p1
p2 ~~ 0.49*p2
p3 ~~ 0.49*p3
i1 ~~ 0.49*i1
i2 ~~ 0.49*i2
i3 ~~ 0.49*i3
a1 ~~ 0.49*a1
a2 ~~ 0.49*a2
a3 ~~ 0.49*a3
sn1 ~~ 0.49*sn1
sn2 ~~ 0.49*sn2
sn3 ~~ 0.49*sn3
pbc1 ~~ 0.49*pbc1
pbc2 ~~ 0.49*pbc2
pbc3 ~~ 0.49*pbc3
pbc4  ~~ 0.49*pbc4
in1~~ 0.49*in1
in2~~ 0.49*in2
in3~~ 0.49*in3
pb1 ~~ 1*pb1

#structural model

att ~ -0.50*sti  + 0.50*pc + 0.50*ic
int ~ 0.50*att + 0.50*sn + 0.50*pbc + 0.50*pb + 0.5*gender + 0.5*age + 0.5*fs +0.5*nationality + 0.5*income `

#simulate population model for each group and combine into dataframe

popDatamodela <- simulateData(popModela, sample.nobs = 10000)
popDatamodelb <- simulateData(popModelb, sample.nobs = 10000)
popData <- rbind(popDatamodela, popDatamodelb)
popData <- data.frame(popData, group = rep(c(1, 2), each = 100000))

analysis.mod1  <- `
#define latent variables
sti =~ s1 + s2 + s3
pc =~ p1 + p2 + p3
ic =~ i1 + i2 + i3
att =~ a1 + a2 + a3
sn =~ sn1 + sn2 + sn3
pbc =~ pb1 + pb2 + pb3 + pb4
int =~ in1 + in2 + in3
pb =~ pb1

#specify structural model

att ~ c(b8, z8)*sti+ c(b10,z10)*pc + c(b11, z11)*ic
int ~ c(b2, z2)*att + c(b4, z4)*sn + c(b6, z6)*pbc + c(b7, z7)*pb + c(b1, z1)*sti + c(b12, z12)*pc + c(b3, z3)*ic + c(b12, z12)*gender + c(b13, z13)*age + c(b14,z14)*fs +(b15, z15)*nationality + c(b16,z16)*income 

#indirect effects group a
st.att.int:= b8*b2
pc.att.int := b10*b2
[ic.att.int](http://ic.att.int/) := b11*b2

#indirect effects group b
st.att.int := z8*z2
pc.att.int:= z10*z2
ic.att.int := z11*z2

#total effects group a
                 
tt.st := b1 + b8*b2
tt.pc := b12 +b10*b2
tt.ic := b3 + b11*b2

#total effects group b
                 
tt.st:= z1 + z8*z2
tt.pc := z12 +z10*z2
tt.ic := z3 + z11*z2`
med.n1 <- sim(NULL,  model = analysis.mod1, n=list(500,500), rawData = popData, group = "group", [std.lv](http://std.lv/) = TRUE, estimator = "MLR", lavaanfun = "sem")
summary(med.n1)
powTable2 <- getPower(med.n1)
findPower(powTable2, "N", 0.85)

**Comment by TDJorgensen** [comment]
Have you read through Vignette 24, available from simsem.org?  Here is the version using matrix-style specification:

https://github.com/simsem/simsem/wiki/Example-24:-Nested-Model-Comparison

The equivalent using `lavaan` syntax for specification (like your examples) is here:

https://github.com/simsem/simsem/blob/master/SupportingDocs/Examples/Version05/ex24/ex24.R

FYI, the syntax you provide would be readable/usable if you embed it in back-ticks.

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

`simsem` is not set up for multiple simultaneous model comparisons.  You would have to repeat this procedure for each pair of models you want to compare.

**Comment by bugiu** [comment]
I read these 2 vignettes, but I don't know how to include the control variables and the mediation effects in the analysis model. I don't understand how to write the analysis model. I need to test this model against two countries, so I don't have multiple simultaneous model comparisons, am I right? I expected my model wouldn't change based on the country type.

**Comment by TDJorgensen** [comment]
This vignette includes both mediation and simulation of exogenous covariates:

https://github.com/simsem/simsem/blob/master/SupportingDocs/Examples/Version05/exMultipleFormat/moderatedMediation.R
